import {AppStatus, TradeSecurity} from "../store/model/Model";

export default async function getAllTrades(): Promise<TradeSecurity[]>
{
    return  [{
        id: "ASTR",
        name: "Астралинукс",
        stepCof: 0.01636,
        defaultStep: 2,
        precision: 0.05,
        accuracy: 2,
        accuracyCurrency: 2,
        minVolume: 1,
        margin: 0.003,
        maxApplicationsVolumes: 5,
        trades: {
            downApplication: [
                {
                    id: 2,
                    order: 1,
                    status: AppStatus.ToClose,
                    byStart: 380.55,
                    byFact: null,
                    byDate: null,
                    byPlanned: 380.55,
                    volume: 1,
                    diff: 6.35,
                    precisionForSchedule: 3,
                    shellPlanned: 386.90,
                    shellDate: new Date(2025, 5, 22, 15, 0, 0),
                    shellFact: 386.90,
                    shellStart: 386.90,
                    compensation: null,
                    profit: 4.05,
                    profitCompensation: 0.81,
                    comment: "Сделка вниз не закрывать."
                },
                {
                    id: 3,
                    order: 2,
                    status: AppStatus.Planned,
                    // status: AppStatus.Planned,
                    // status: AppStatus.ToOpen,
                    // status: AppStatus.Opened,
                    // status: AppStatus.ToClose,
                    // status: AppStatus.Closed,
                    // status: AppStatus.Result,
                    byStart: 382.65,
                    byFact: null,
                    byDate: null,
                    byPlanned: 382.65,
                    volume: 1,
                    diff: 6.40,
                    precisionForSchedule: 3,
                    shellPlanned: 389.05,
                    shellDate: null,
                    shellFact: null,
                    shellStart: 389.05,
                    compensation: null,
                    profit: 4.08,
                    profitCompensation: 0.82,
                    comment: "Сделка вниз - не открытая."
                }
            ],
            upApplication: [
                {
                    id: 4,
                    order: 1,
                    status: AppStatus.ToClose,
                    byStart: 396.50,
                    byFact: 396.50,
                    byDate: new Date(2025, 5, 20, 15, 1, 1),
                    byPlanned: 396.50,
                    volume: 1,
                    diff: 6.65,
                    precisionForSchedule: 1,
                    shellPlanned: 403.15,
                    shellDate: null,
                    shellFact: null,
                    shellStart: 403.15,
                    compensation: null,
                    profit: 4.25,
                    profitCompensation: 0.85,
                    comment: "Сделка вверх не закрывать."
                },
                {
                    id: 5,
                    order: 2,
                    status: AppStatus.Planned,
                    byStart: 382.50,
                    byFact: null,
                    byDate: null,
                    byPlanned: 382.50,
                    volume: 1,
                    diff: 6.40,
                    precisionForSchedule: 1,
                    shellPlanned: 388.90,
                    shellDate: null,
                    shellFact: null,
                    shellStart: 388.90,
                    compensation: null,
                    profit: 4.09,
                    profitCompensation: 0.82,
                    comment: "Сделка вверх не закрывать."
                }
            ],
            history: [
                {
                    id: 6,
                    order: 1,
                    status: AppStatus.Result,
                    byStart: 389.95,
                    byFact: 389.95,
                    byDate: new Date(2025, 5, 20, 15, 1, 1),
                    byPlanned: 389.95,
                    volume: 1,
                    diff: -5.30,
                    precisionForSchedule: 1,
                    shellPlanned: 396.50,
                    shellDate: new Date(2025, 5, 20, 15, 1, 1),
                    shellFact: 384.65,
                    shellStart: 396.5,
                    compensation: 11.85,
                    profit: 11.85,
                    profitCompensation: 4.19,
                    comment: "закрыто"
                },
                {
                    id: 7,
                    order: 2,
                    status: AppStatus.Result,
                    byStart: 395.65,
                    byFact: 395.65,
                    byDate: new Date(2025, 5, 20, 15, 1, 1),
                    byPlanned: 395.65,
                    volume: 1,
                    diff: 6.60,
                    precisionForSchedule: 3,
                    shellPlanned: 402.25,
                    shellDate: new Date(2025, 5, 20, 15, 1, 1),
                    shellFact: 402.25,
                    shellStart: 402.25,
                    compensation: null,
                    profit: 4.21,
                    profitCompensation: 0.84,
                    comment: "закрыто"
                }
            ],
        },
    }];
}